"""
Assignment Service — business logic for Feature #3: Ticket Assignment Recommendation.

Workflow:
1. Fetch the ticket from Athena by ID
2. Build a search query from the ticket's title + description
3. Semantic search for relevant documentation and similar tickets
4. Call the LLM with ticket details + context + support group mappings
5. Parse the structured JSON recommendation

Support groups are loaded from exploration/output/assignable_support_groups.json,
which contains all 309 IR and 310 SR assignable groups (disabled groups excluded).
If the JSON file is unavailable, a minimal fallback set is used.
"""

import asyncio
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from src.clients.athena_client import AthenaClient
from src.clients.databricks_client import DatabricksClient
from src.models.assignment import (
    AssignmentRecommendation,
    AssignmentResponse,
    TicketInfo,
)
from src.models.chat import SourceCitation, SourceType

logger = logging.getLogger(__name__)

# ── Support Group Loading ─────────────────────────────────────────────
# Groups are loaded from the JSON file generated by
# exploration/explore_assignable_support_groups.py.
# Only groups with disabled=false in the Athena enum tree are included.

# Path to the JSON file (relative to project root)
_SUPPORT_GROUPS_JSON = (
    Path(__file__).resolve().parent.parent.parent
    / "exploration"
    / "output"
    / "assignable_support_groups.json"
)

# Minimal fallback if JSON file is unavailable — only the most essential groups
_FALLBACK_IR_SUPPORT_GROUPS: dict[str, str] = {
    "Service Desk": "ec749166-07c5-eba6-35ba-bd32fa8ed7d2",
    "Service Desk\\ATLAS": "b4b69f54-24f4-0a43-83f4-d3d7dccc8440",
    "Service Desk\\Service Desk - Epic": "8e706a5a-a6e6-7a9e-a308-481846a8dce1",
}

_FALLBACK_SR_SUPPORT_GROUPS: dict[str, str] = {
    "Service Desk": "043871eb-f69c-2330-7cbb-155b04fe24ea",
    "Service Desk\\ATLAS": "dbfd82aa-f0a7-56b9-d0c5-4ba1e0e1ebc4",
    "Service Desk\\Service Desk - Epic": "5a937757-7e0a-c22d-7967-05202a369b87",
}


def load_support_groups(
    json_path: Path | None = None,
) -> tuple[dict[str, str], dict[str, str]]:
    """
    Load assignable support groups from the JSON file.

    Args:
        json_path: Path to the JSON file. Defaults to the standard location.

    Returns:
        Tuple of (ir_support_groups, sr_support_groups) dicts mapping
        fullname → GUID.
    """
    path = json_path or _SUPPORT_GROUPS_JSON

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        ir_groups: dict[str, str] = {}
        for entry in data.get("ir_assignable", []):
            ir_groups[entry["fullname"]] = entry["guid"]

        sr_groups: dict[str, str] = {}
        for entry in data.get("sr_assignable", []):
            sr_groups[entry["fullname"]] = entry["guid"]

        if not ir_groups or not sr_groups:
            logger.warning(
                "Support groups JSON at %s has empty lists. Using fallback.", path
            )
            return (
                _FALLBACK_IR_SUPPORT_GROUPS.copy(),
                _FALLBACK_SR_SUPPORT_GROUPS.copy(),
            )

        logger.info(
            "Loaded %d IR and %d SR assignable support groups from %s",
            len(ir_groups),
            len(sr_groups),
            path,
        )
        return ir_groups, sr_groups

    except FileNotFoundError:
        logger.warning(
            "Support groups JSON not found at %s. Using fallback set. "
            "Run exploration/explore_assignable_support_groups.py to generate it.",
            path,
        )
        return (
            _FALLBACK_IR_SUPPORT_GROUPS.copy(),
            _FALLBACK_SR_SUPPORT_GROUPS.copy(),
        )
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        logger.warning(
            "Failed to parse support groups JSON at %s: %s. Using fallback.", path, exc
        )
        return (
            _FALLBACK_IR_SUPPORT_GROUPS.copy(),
            _FALLBACK_SR_SUPPORT_GROUPS.copy(),
        )


# Load at module import time
IR_SUPPORT_GROUPS, SR_SUPPORT_GROUPS = load_support_groups()

ASSIGNMENT_SYSTEM_PROMPT = """\
You are an AI assistant for the Penn Medicine / UPHS IT Service Desk. \
Your task is to analyze a ticket and recommend the best support group assignment and priority level.

You must respond with ONLY a valid JSON object (no markdown, no code fences, no extra text) \
with exactly these keys:
- "support_group_name": The name of the recommended support group from the list below
- "support_group_guid": The GUID of the recommended support group from the list below
- "priority": The recommended priority level
- "rationale": A brief explanation (2-4 sentences) of why you chose this group and priority

AVAILABLE SUPPORT GROUPS (name → GUID):
{support_groups}

PRIORITY GUIDANCE:
- For incidents (IR): Use numeric priority 1 (critical) through 4 (low). \
Consider impact and urgency.
- For service requests (SR): Use "Immediate", "High", "Medium", or "Low". \
Consider business impact and time sensitivity.

LOCATION-BASED ROUTING RULES:
When the ticket involves hardware, desktop, printer, workstation, network jack, phone, \
or end-user support issues, the ticket's physical location determines which EUS sub-group \
to assign. ALWAYS match the ticket location to the correct location-specific sub-group:

- Location starts with "CAMPUS" → EUS\\Campus
- Location starts with "CCH" → EUS\\CCH
- Location starts with "HUP Cedar" → EUS\\HUP Cedar
- Location starts with "HUP Pavilion" → EUS\\HUP\\HUP Pavilion
- Location starts with "HUP" (not Cedar/Pavilion) → EUS\\HUP
- Location starts with "Princeton" or "MCP" → EUS\\MCP
- Location starts with "PAH" → EUS\\PaH
- Location starts with "PCAM" → EUS\\PCAM
- Location starts with "PMaH" → check sub-location for BALA, KOP, or West Chester
- Location starts with "PMUC" → EUS\\PMUC
- Location starts with "PPMC" → EUS\\PPMC
- Location starts with "RITT" → EUS\\RITT
- Location starts with "Remote sites" or "RSI" → EUS\\RSI
- Location starts with "Doylestown" or "PMDH" → PMDH Dispatch\\PMDH EUS
- Location starts with "LGH" or "LGHP" → LGH\\Shared Services (LGH)\\PC Technicians (LGH) \
(choose Hospital, Commercial, Road, SOP, or Printing sub-group as appropriate)
- Location is "Community Connect" → EUS\\RSI (treated as remote site)
- Location is "Remote User" → EUS\\Campus (default for remote workers)
- Location is "Data Center" → Technology\\Infrastructure (not EUS)

For non-EUS issues at specific locations, location still matters:
- LGH/LGHP locations with Epic issues → LGH\\Epic (LGH)\\... sub-groups
- LGH/LGHP locations with network issues → LGH\\Technical Services (LGH)\\Network (LGH)
- PMDH locations with network issues → PMDH Dispatch\\PMDH Network Team
- PMDH locations with application issues → PMDH Dispatch\\PMDH Legacy Applications or PMDH ECW
- All other locations → use the standard (non-location-specific) groups

IMPORTANT: The location field is CRITICAL for EUS-type issues. Never default to EUS\\Campus \
when the ticket location clearly indicates a different site. Always match the ticket's \
location to the correct location-specific sub-group.

CONTEXT FROM KNOWLEDGE BASE AND SIMILAR TICKETS:
{context}"""


class AssignmentService:
    """Orchestrates the ticket assignment recommendation pipeline."""

    def __init__(
        self,
        athena_client: AthenaClient,
        databricks_client: DatabricksClient,
    ) -> None:
        self._athena = athena_client
        self._databricks = databricks_client

    async def recommend_assignment(
        self,
        ticket_id: str,
        top_k_docs: int = 5,
        top_k_tickets: int = 5,
        max_tokens: int = 2048,
    ) -> AssignmentResponse:
        """
        Analyze a ticket and recommend a support group assignment and priority.

        Args:
            ticket_id: Ticket ID (e.g., 'IR1959493' or 'SR1959584').
            top_k_docs: Number of documentation articles to retrieve.
            top_k_tickets: Number of similar tickets to retrieve.
            max_tokens: Maximum tokens in the LLM response.

        Returns:
            AssignmentResponse with ticket info, recommendation, and sources.

        Raises:
            ValueError: If the ticket ID prefix is not recognized.
        """
        # Step 1: Determine ticket type and fetch
        ticket_type = self._get_ticket_type(ticket_id)
        raw_ticket = await self._athena.get_ticket(ticket_id)

        # Step 2: Extract ticket info
        ticket_info = self._extract_ticket_info(raw_ticket, ticket_id, ticket_type)

        # Step 3: Build search query from ticket content
        search_text = self._build_search_text(ticket_info)

        # Step 4: Generate embedding and run semantic search
        query_embedding = await self._databricks.generate_embedding(search_text)

        loop = asyncio.get_event_loop()
        doc_results, ticket_results = await asyncio.gather(
            loop.run_in_executor(
                None,
                self._databricks.find_similar_documentation,
                query_embedding,
                top_k_docs,
            ),
            loop.run_in_executor(
                None,
                self._databricks.find_similar_by_embedding,
                query_embedding,
                "scratchpad.aslanuka.ir_embeddings",
                "ticket_embedding",
                "id",
                top_k_tickets,
            ),
        )

        # Step 5: Build sources
        sources = self._build_sources(doc_results, ticket_results)

        # Step 6: Build LLM prompt and call
        support_groups = IR_SUPPORT_GROUPS if ticket_type == "incident" else SR_SUPPORT_GROUPS
        context = self._build_context(doc_results, ticket_results)
        messages = self._build_llm_messages(
            ticket_info=ticket_info,
            support_groups=support_groups,
            context=context,
        )

        llm_response = await self._databricks.call_llm(messages, max_tokens=max_tokens)

        # Step 7: Parse recommendation
        recommendation = self._parse_recommendation(llm_response, support_groups)

        return AssignmentResponse(
            ticket=ticket_info,
            recommendation=recommendation,
            sources=sources,
        )

    # ── Private Helpers ───────────────────────────────────────────────

    @staticmethod
    def _get_ticket_type(ticket_id: str) -> str:
        """Determine ticket type from the ID prefix."""
        upper_id = ticket_id.upper()
        if upper_id.startswith("IR"):
            return "incident"
        elif upper_id.startswith("SR"):
            return "servicerequest"
        else:
            raise ValueError(
                f"Unknown ticket type prefix in '{ticket_id}'. Expected IR or SR."
            )

    @staticmethod
    def _format_datetime(raw_date: str | None) -> str | None:
        """Format an ISO 8601 datetime string to 'HH:MM MM/DD/YYYY'."""
        if not raw_date:
            return None
        try:
            dt = datetime.fromisoformat(raw_date)
            return dt.strftime("%H:%M %m/%d/%Y")
        except (ValueError, TypeError):
            return raw_date

    @staticmethod
    def _extract_ticket_info(
        raw: dict[str, Any],
        ticket_id: str,
        ticket_type: str,
    ) -> TicketInfo:
        """Extract a TicketInfo from a raw Athena ticket response."""
        affected_user_raw = raw.get("affectedUser")
        affected_user = None
        affected_user_title = None
        if isinstance(affected_user_raw, dict):
            affected_user = affected_user_raw.get("displayName") or affected_user_raw.get("userName")
            affected_user_title = affected_user_raw.get("title")

        support_group = raw.get("supportGroup")
        if isinstance(support_group, dict):
            support_group = support_group.get("name") or support_group.get("displayName")

        status = raw.get("status")
        if isinstance(status, dict):
            status = status.get("name") or status.get("displayName")

        location = raw.get("location")
        if isinstance(location, dict):
            location = location.get("name") or location.get("displayName")

        priority = raw.get("priority")
        if isinstance(priority, dict):
            priority = priority.get("name") or priority.get("displayName")

        return TicketInfo(
            id=raw.get("id", ticket_id),
            ticket_type=ticket_type,
            title=raw.get("title"),
            description=raw.get("description"),
            status=status,
            priority=priority,
            support_group=support_group,
            affected_user=affected_user,
            affected_user_title=affected_user_title,
            location=location,
            created_date=AssignmentService._format_datetime(raw.get("createdDate")),
        )

    @staticmethod
    def _build_search_text(ticket_info: TicketInfo) -> str:
        """Build a search query string from ticket title and description."""
        parts: list[str] = []
        if ticket_info.title:
            parts.append(ticket_info.title)
        if ticket_info.description:
            # Limit description length for embedding
            desc = ticket_info.description[:500]
            parts.append(desc)
        return " ".join(parts) if parts else "IT support ticket"

    @staticmethod
    def _build_sources(
        doc_results: list[dict[str, Any]],
        ticket_results: list[dict[str, Any]],
    ) -> list[SourceCitation]:
        """Build source citations from retrieval results."""
        sources: list[SourceCitation] = []

        for doc in doc_results:
            content = doc.get("content", "")
            preview = content[:200] + "..." if len(content) > 200 else content
            sources.append(
                SourceCitation(
                    type=SourceType.documentation,
                    title=doc.get("title", "Untitled"),
                    similarity=doc.get("similarity", 0.0),
                    content_preview=preview,
                    notebook=doc.get("notebook"),
                    section=doc.get("section"),
                )
            )

        for ticket in ticket_results:
            sources.append(
                SourceCitation(
                    type=SourceType.ticket,
                    title=ticket.get("id", "Unknown"),
                    similarity=ticket.get("similarity", 0.0),
                )
            )

        return sources

    @staticmethod
    def _build_context(
        doc_results: list[dict[str, Any]],
        ticket_results: list[dict[str, Any]],
    ) -> str:
        """Build the context string from retrieval results."""
        parts: list[str] = []

        if doc_results:
            parts.append("=== KNOWLEDGE BASE DOCUMENTATION ===")
            for i, doc in enumerate(doc_results, 1):
                title = doc.get("title", "Untitled")
                section = doc.get("section", "Unknown Section")
                notebook = doc.get("notebook", "unknown")
                content = doc.get("content", "")
                similarity = doc.get("similarity", 0.0)
                parts.append(
                    f"\n--- Document {i} (similarity: {similarity:.3f}) ---\n"
                    f"Notebook: {notebook} | Section: {section} | Title: {title}\n"
                    f"{content}"
                )

        if ticket_results:
            parts.append("\n=== SIMILAR HISTORICAL TICKETS ===")
            for i, ticket in enumerate(ticket_results, 1):
                ticket_id = ticket.get("id", "Unknown")
                similarity = ticket.get("similarity", 0.0)
                parts.append(f"- Ticket {ticket_id} (similarity: {similarity:.3f})")

        if not parts:
            return "No relevant documentation or similar tickets were found."

        return "\n".join(parts)

    @staticmethod
    def _build_llm_messages(
        ticket_info: TicketInfo,
        support_groups: dict[str, str],
        context: str,
    ) -> list[dict[str, str]]:
        """Build the message list for the LLM call."""
        # Format support groups for the prompt
        sg_lines = "\n".join(
            f"  - {name}: {guid}" for name, guid in support_groups.items()
        )

        system_content = ASSIGNMENT_SYSTEM_PROMPT.format(
            support_groups=sg_lines,
            context=context,
        )

        # Build the user message with ticket details
        ticket_details = (
            f"Ticket ID: {ticket_info.id}\n"
            f"Type: {ticket_info.ticket_type}\n"
            f"Title: {ticket_info.title or 'N/A'}\n"
            f"Description: {ticket_info.description or 'N/A'}\n"
            f"Current Status: {ticket_info.status or 'N/A'}\n"
            f"Current Priority: {ticket_info.priority or 'N/A'}\n"
            f"Current Support Group: {ticket_info.support_group or 'N/A'}\n"
            f"Affected User: {ticket_info.affected_user or 'N/A'}\n"
            f"Location: {ticket_info.location or 'N/A'}\n"
            f"Created Date: {ticket_info.created_date or 'N/A'}"
        )

        user_content = (
            f"Please analyze the following ticket and recommend the best support group "
            f"assignment and priority level.\n\n{ticket_details}"
        )

        return [
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ]

    @staticmethod
    def _parse_recommendation(
        llm_response: str,
        support_groups: dict[str, str],
    ) -> AssignmentRecommendation:
        """
        Parse the LLM's JSON response into an AssignmentRecommendation.

        Falls back to a best-effort extraction if JSON parsing fails.
        """
        # Strip any markdown code fences the LLM might add despite instructions
        cleaned = llm_response.strip()
        if cleaned.startswith("```"):
            # Remove opening fence (with optional language tag)
            first_newline = cleaned.index("\n") if "\n" in cleaned else 3
            cleaned = cleaned[first_newline + 1 :]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()

        try:
            data = json.loads(cleaned)
            return AssignmentRecommendation(
                support_group_name=data.get("support_group_name", "Service Desk"),
                support_group_guid=data.get(
                    "support_group_guid",
                    support_groups.get("Service Desk", ""),
                ),
                priority=data.get("priority", "Medium"),
                rationale=data.get("rationale", "Unable to parse rationale from LLM response."),
            )
        except (json.JSONDecodeError, KeyError, TypeError) as exc:
            logger.warning("Failed to parse LLM JSON response: %s. Raw: %s", exc, llm_response[:200])
            # Fallback: return a default recommendation with the raw response as rationale
            return AssignmentRecommendation(
                support_group_name="Service Desk",
                support_group_guid=support_groups.get("Service Desk", ""),
                priority="Medium",
                rationale=f"LLM response could not be parsed as JSON. Raw response: {llm_response[:500]}",
            )