"""
Assignment Service — business logic for Feature #3: Ticket Assignment Recommendation.

Simplified pipeline using TF-IDF classifier (replaces LLM):
1. Fetch the ticket from Athena by ID
2. Check specific triage rules (12 data-driven patterns)
3. Check Service Desk triage rules (password reset, MyChart, etc.)
4. Run TF-IDF classifier for support group prediction
5. Resolve GUID from support group name
6. Return recommendation with confidence and alternatives

Support groups are loaded from exploration/output/assignable_support_groups.json,
which contains all 309 IR and 310 SR assignable groups (disabled groups excluded).
If the JSON file is unavailable, a minimal fallback set is used.
"""

import json
import logging
from pathlib import Path
from typing import Any

from src.clients.athena_client import AthenaClient
from src.models.assignment import (
    AssignmentRecommendation,
    AssignmentResponse,
    ClassifierPrediction,
    TicketInfo,
)
from src.services.ticket_classifier import TicketClassifier, get_ticket_classifier

logger = logging.getLogger(__name__)

# ── Support Group Loading ─────────────────────────────────────────────
# Groups are loaded from the JSON file generated by
# exploration/explore_assignable_support_groups.py.
# Only groups with disabled=false in the Athena enum tree are included.

# Path to the JSON file (relative to project root)
_SUPPORT_GROUPS_JSON = (
    Path(__file__).resolve().parent.parent.parent
    / "exploration"
    / "output"
    / "assignable_support_groups.json"
)

# Minimal fallback if JSON file is unavailable — only the most essential groups
_FALLBACK_IR_SUPPORT_GROUPS: dict[str, str] = {
    "Service Desk": "ec749166-07c5-eba6-35ba-bd32fa8ed7d2",
    "Service Desk\\ATLAS": "b4b69f54-24f4-0a43-83f4-d3d7dccc8440",
    "Service Desk\\Service Desk - Epic": "8e706a5a-a6e6-7a9e-a308-481846a8dce1",
}

_FALLBACK_SR_SUPPORT_GROUPS: dict[str, str] = {
    "Service Desk": "043871eb-f69c-2330-7cbb-155b04fe24ea",
    "Service Desk\\ATLAS": "dbfd82aa-f0a7-56b9-d0c5-4ba1e0e1ebc4",
    "Service Desk\\Service Desk - Epic": "5a937757-7e0a-c22d-7967-05202a369b87",
}


def load_support_groups(
    json_path: Path | None = None,
) -> tuple[dict[str, str], dict[str, str]]:
    """
    Load assignable support groups from the JSON file.

    Returns:
        Tuple of (ir_support_groups, sr_support_groups) dicts mapping
        fullname → GUID.
    """
    path = json_path or _SUPPORT_GROUPS_JSON

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        ir_groups: dict[str, str] = {}
        for entry in data.get("ir_assignable", []):
            ir_groups[entry["fullname"]] = entry["guid"]

        sr_groups: dict[str, str] = {}
        for entry in data.get("sr_assignable", []):
            sr_groups[entry["fullname"]] = entry["guid"]

        if not ir_groups or not sr_groups:
            logger.warning(
                "Support groups JSON at %s has empty lists. Using fallback.", path
            )
            return (
                _FALLBACK_IR_SUPPORT_GROUPS.copy(),
                _FALLBACK_SR_SUPPORT_GROUPS.copy(),
            )

        logger.info(
            "Loaded %d IR and %d SR assignable support groups from %s",
            len(ir_groups),
            len(sr_groups),
            path,
        )
        return ir_groups, sr_groups

    except FileNotFoundError:
        logger.warning(
            "Support groups JSON not found at %s. Using fallback set.", path
        )
        return (
            _FALLBACK_IR_SUPPORT_GROUPS.copy(),
            _FALLBACK_SR_SUPPORT_GROUPS.copy(),
        )
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        logger.warning(
            "Failed to parse support groups JSON at %s: %s. Using fallback.", path, exc
        )
        return (
            _FALLBACK_IR_SUPPORT_GROUPS.copy(),
            _FALLBACK_SR_SUPPORT_GROUPS.copy(),
        )


# Load at module import time
IR_SUPPORT_GROUPS, SR_SUPPORT_GROUPS = load_support_groups()


# ═══════════════════════════════════════════════════════════════════════
# SERVICE DESK TRIAGE RULES
# ═══════════════════════════════════════════════════════════════════════
# These patterns should ALWAYS route to Service Desk.
# Based on benchmark: 20% of SD tickets were over-routed to specialized groups.

SERVICE_DESK_TRIAGE_PATTERNS = [
    {
        "name": "password_reset",
        "keywords": ["password reset", "pw reset", "reset password", "password unlock",
                     "account locked", "account lockout", "login blocked",
                     "inactive for too many days", "blocked out"],
        "negative": ["pennchart access", "epic access", "provisioning"],
    },
    {
        "name": "mypennmedicine",
        "keywords": ["mypennmedicine", "mychart", "patient portal",
                     "mypennchart", "my penn medicine"],
        "negative": [],
    },
    {
        "name": "general_inquiry",
        "keywords": ["caller decided to end", "ended call", "hung up",
                     "general inquiry", "general question"],
        "negative": [],
    },
    {
        "name": "basic_account",
        "keywords": ["sd password reset", "pennid", "dob verified",
                     "username verified", "verification questions"],
        "negative": ["pennchart", "epic", "provisioning"],
    },
]


# ═══════════════════════════════════════════════════════════════════════
# SPECIFIC TRIAGE RULES (Phase 2c-2f)
# ═══════════════════════════════════════════════════════════════════════
# Data-driven rules based on actual ticket text analysis from benchmark.
# These run BEFORE Service Desk triage to prevent false positives.

SPECIFIC_TRIAGE_PATTERNS = [
    {
        "name": "security_engineering_lgh_ldap",
        "target_group": "Security Engineering",
        "keywords": ["lha.org", "lgh.org:389"],
        "context_keywords": [],
        "negative": ["hris support form"],
        "description": "LGH LDAP errors → Security Engineering (not Kronos).",
    },
    {
        "name": "security_engineering_estar_lgh",
        "target_group": "Security Engineering",
        "keywords": ["estar portal", "estar timestamp", "estar workforce",
                     "e-star portal", "e star portal"],
        "context_keywords": ["lancaster", "lgh"],
        "negative": ["hris support form"],
        "description": "eStar Portal/Timestamp/Workforce at LGH → Security Engineering.",
    },
    {
        "name": "hris_estar_kronos",
        "target_group": "Kronos",
        "keywords": ["hris support form"],
        "context_keywords": ["estar", "e-star", "e star"],
        "negative": ["transfer", "reporting change", "network access", "email access",
                     "remove employee", "no longer employee"],
        "description": "HRIS Support Form + eStar context → Kronos.",
    },
    {
        "name": "iam_authentication",
        "target_group": "IAM - Single Sign On",
        "keywords": ["ms authenticator", "microsoft authenticator",
                     "authenticator app", "authentication loop",
                     "ms authentiator", "microsoft authentiator",
                     "prompting for authenticator", "prompting for ms authenticator"],
        "context_keywords": [],
        "negative": ["duo enrollment", "duo setup", "hardware repair", "hardware support"],
        "description": "MS Authenticator / authentication loop → IAM-SSO.",
    },
    {
        "name": "hris_form_kronos",
        "target_group": "Kronos",
        "keywords": ["hris support form"],
        "context_keywords": ["paid time off", "parental time", "parental leave",
                            "fmla", "ppt", "pto"],
        "negative": ["transfer", "reporting change", "network access", "email access",
                     "remove employee", "no longer employee"],
        "description": "HRIS forms about PTO/leave → Kronos.",
    },
    {
        "name": "estar_login_kronos",
        "target_group": "Kronos",
        "keywords": ["estar", "e-star", "e star"],
        "context_keywords": ["log in", "login", "logon", "log on", "sign in",
                            "unable to access", "unable to log", "cannot log",
                            "can't log", "can not log"],
        "negative": ["lha.org", "lgh.org:389", "estar portal", "estar timestamp",
                     "estar workforce", "e-star portal", "e star portal",
                     "hris support form"],
        "description": "Generic eStar login issues → Kronos (Security Eng rules take priority).",
    },
    {
        "name": "hup_west_ravdin",
        "target_group": "HUP West",
        "keywords": [],
        "context_keywords": [],
        "negative": [],
        "location_keywords": ["ravdin", "rhoads", "maloney"],
        "description": "RAVDIN/RHOADS/MALONEY buildings → HUP West.",
    },
    {
        "name": "aria_upgrade_command_center",
        "target_group": "Command Center Support",
        "keywords": ["aria upgrade", "aria v18", "aria issue"],
        "context_keywords": [],
        "negative": ["billing code", "missing provider"],
        "description": "Aria upgrade/version issues → Command Center Support.",
    },
    {
        "name": "riskonnect_is_event_isaac",
        "target_group": "ISAAC",
        "keywords": ["riskonnect event - information systems"],
        "context_keywords": [],
        "negative": [],
        "description": "Riskonnect IS events → ISAAC.",
    },
    {
        "name": "riskonnect_privacy_isaac",
        "target_group": "ISAAC",
        "keywords": ["riskonnect event - privacy"],
        "context_keywords": [],
        "negative": [],
        "description": "Riskonnect privacy events → ISAAC.",
    },
    {
        "name": "windows_defender_lockout_cyber",
        "target_group": "Cyber Defense and Operations",
        "keywords": ["windows defender", "defender has locked", "defender locked"],
        "context_keywords": [],
        "negative": [],
        "description": "Windows Defender lockouts → Cyber Defense and Operations.",
    },
    {
        "name": "pcam_hardware_location",
        "target_group": "PCAM",
        "keywords": [],
        "context_keywords": [],
        "negative": [],
        "location_keywords": ["pcam", "s. pavillion", "south pavilion"],
        "description": "Hardware tickets at PCAM/S. Pavillion → PCAM.",
    },
]


# ═══════════════════════════════════════════════════════════════════════
# TRIAGE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════


def check_service_desk_triage(title: str, description: str) -> bool:
    """
    Check if a ticket matches Service Desk triage patterns.
    Returns True if the ticket should be assigned to Service Desk.
    """
    text = f"{title} {description}".lower()

    for pattern in SERVICE_DESK_TRIAGE_PATTERNS:
        has_positive = any(kw in text for kw in pattern["keywords"])
        if not has_positive:
            continue

        has_negative = any(kw in text for kw in pattern.get("negative", []))
        if has_negative:
            continue

        return True

    return False


def check_specific_triage(
    title: str, description: str, location: str, support_groups: dict[str, str]
) -> tuple[str, str] | None:
    """
    Check if a ticket matches specific triage patterns (Phase 2c-2f).
    Returns (group_name, guid) if matched, None otherwise.
    """
    text = f"{title} {description}".lower()
    location_lower = (location or "").lower()

    for pattern in SPECIFIC_TRIAGE_PATTERNS:
        location_kws = pattern.get("location_keywords", [])
        primary_kws = pattern.get("keywords", [])

        if location_kws and not primary_kws:
            # Pure location-based rule
            has_location = any(kw in location_lower for kw in location_kws)
            if not has_location:
                continue
        else:
            # Standard text-based matching
            has_primary = any(kw in text for kw in primary_kws)
            if not has_primary:
                continue

            # If context_keywords exist, at least one must match (text OR location)
            context_kws = pattern.get("context_keywords", [])
            if context_kws:
                has_context = any(
                    kw in text or kw in location_lower for kw in context_kws
                )
                if not has_context:
                    continue

        # Check negatives
        has_negative = any(kw in text for kw in pattern.get("negative", []))
        if has_negative:
            continue

        # Find the target group in support_groups
        target = pattern["target_group"]
        if target in support_groups:
            return target, support_groups[target]

        # Try leaf match (e.g., "Kronos" matches "Applications\\...\\Kronos")
        target_lower = target.lower()
        for name, guid in support_groups.items():
            if name.lower() == target_lower or name.lower().endswith("\\" + target_lower):
                return name, guid

    return None


# ═══════════════════════════════════════════════════════════════════════
# GUID RESOLUTION
# ═══════════════════════════════════════════════════════════════════════


def resolve_group_guid(
    predicted_group: str, support_groups: dict[str, str]
) -> str:
    """
    Resolve a classifier-predicted group name to its GUID.

    The classifier predicts short/leaf names (e.g., "HUP", "Kronos").
    We need to find the matching full path in the support_groups dict.

    Returns the GUID if found, empty string otherwise.
    """
    if not predicted_group:
        return ""

    # Direct match
    if predicted_group in support_groups:
        return support_groups[predicted_group]

    # Leaf match: classifier predicts "HUP" → matches "EUS\\HUP"
    predicted_lower = predicted_group.lower()
    for full_name, guid in support_groups.items():
        leaf = full_name.rsplit("\\", 1)[-1].strip()
        if leaf.lower() == predicted_lower:
            return guid

    # Partial/contains match
    for full_name, guid in support_groups.items():
        if predicted_lower in full_name.lower():
            return guid

    return ""


# ═══════════════════════════════════════════════════════════════════════
# ASSIGNMENT SERVICE
# ═══════════════════════════════════════════════════════════════════════


class AssignmentService:
    """Orchestrates the ticket assignment recommendation pipeline."""

    def __init__(
        self,
        athena_client: AthenaClient,
        classifier: TicketClassifier | None = None,
    ) -> None:
        self._athena = athena_client
        self._classifier = classifier or get_ticket_classifier()

    async def recommend_assignment(
        self,
        ticket_id: str,
        top_k: int = 5,
    ) -> AssignmentResponse:
        """
        Analyze a ticket and recommend a support group assignment.

        Pipeline:
        1. Validate and fetch ticket from Athena
        2. Check specific triage rules (12 data-driven patterns)
        3. Check Service Desk triage rules
        4. Run TF-IDF classifier for prediction
        5. Resolve GUID and return recommendation

        Args:
            ticket_id: Ticket ID (e.g., 'IR1959493' or 'SR1959584').
            top_k: Number of alternative predictions to include.

        Returns:
            AssignmentResponse with ticket info and recommendation.

        Raises:
            ValueError: If the ticket ID prefix is not recognized.
        """
        # Step 0: Validate and normalize the ticket ID
        ticket_id = self._validate_and_normalize_ticket_id(ticket_id)

        # Step 1: Determine ticket type and fetch
        ticket_type = self._get_ticket_type(ticket_id)
        raw_ticket = await self._athena.get_ticket(ticket_id)

        # Step 2: Extract ticket info
        ticket_info = self._extract_ticket_info(raw_ticket, ticket_id, ticket_type)

        # Select support groups for this ticket type
        support_groups = IR_SUPPORT_GROUPS if ticket_type == "incident" else SR_SUPPORT_GROUPS

        # Step 3a: Check specific triage rules (Phase 2c-2f)
        specific_match = check_specific_triage(
            ticket_info.title or "",
            ticket_info.description or "",
            ticket_info.location or "",
            support_groups,
        )
        if specific_match:
            group_name, group_guid = specific_match
            recommendation = AssignmentRecommendation(
                support_group_name=group_name,
                support_group_guid=group_guid,
                confidence=1.0,
                method="triage_rule",
                alternatives=[],
            )
            return AssignmentResponse(
                ticket=ticket_info,
                recommendation=recommendation,
            )

        # Step 3b: Check Service Desk triage rules
        if check_service_desk_triage(
            ticket_info.title or "",
            ticket_info.description or "",
        ):
            sd_guid = support_groups.get("Service Desk", "")
            recommendation = AssignmentRecommendation(
                support_group_name="Service Desk",
                support_group_guid=sd_guid,
                confidence=1.0,
                method="triage_rule",
                alternatives=[],
            )
            return AssignmentResponse(
                ticket=ticket_info,
                recommendation=recommendation,
            )

        # Step 4: Run TF-IDF classifier
        predictions = self._classifier.predict(
            title=ticket_info.title or "",
            description=ticket_info.description or "",
            ticket_type="Incident" if ticket_type == "incident" else "Service Request",
            location=ticket_info.location or "",
            classification=ticket_info.classification or "",
            source=ticket_info.source or "",
            top_k=top_k,
        )

        if not predictions:
            # Fallback: assign to Service Desk
            sd_guid = support_groups.get("Service Desk", "")
            recommendation = AssignmentRecommendation(
                support_group_name="Service Desk",
                support_group_guid=sd_guid,
                confidence=0.0,
                method="classifier",
                alternatives=[],
            )
            return AssignmentResponse(
                ticket=ticket_info,
                recommendation=recommendation,
            )

        # Step 5: Resolve GUID for top prediction
        top_prediction = predictions[0]
        top_group = top_prediction["support_group"]
        top_confidence = top_prediction["confidence"]
        top_guid = resolve_group_guid(top_group, support_groups)

        # Build alternatives (predictions 2 through N)
        alternatives = [
            ClassifierPrediction(
                support_group=p["support_group"],
                confidence=p["confidence"],
            )
            for p in predictions[1:]
            if p["confidence"] > 0.001  # Only include meaningful alternatives
        ]

        recommendation = AssignmentRecommendation(
            support_group_name=top_group,
            support_group_guid=top_guid,
            confidence=top_confidence,
            method="classifier",
            alternatives=alternatives,
        )

        return AssignmentResponse(
            ticket=ticket_info,
            recommendation=recommendation,
        )

    # ── Private Helpers ───────────────────────────────────────────────

    @staticmethod
    def _validate_and_normalize_ticket_id(ticket_id: str) -> str:
        """
        Validate and normalize a ticket ID.

        Strips whitespace, uppercases, and checks format.
        Returns the normalized ticket ID (e.g., 'IR1959493').

        Raises:
            ValueError: With a specific, user-friendly message for each error case.
        """
        if not ticket_id or not ticket_id.strip():
            raise ValueError(
                "Ticket ID is required. Please enter a ticket ID "
                "(e.g., 'IR1959493' or 'SR1959584')."
            )

        normalized = ticket_id.strip().upper()

        valid_prefixes = ("IR", "SR")
        if not any(normalized.startswith(p) for p in valid_prefixes):
            raise ValueError(
                f"Ticket ID '{normalized}' must start with 'IR' (Incident) or 'SR' (Service Request). "
                f"Example: 'IR1959493' or 'SR1959584'."
            )

        numeric_part = normalized[2:]
        if not numeric_part.isdigit():
            raise ValueError(
                f"Ticket ID '{normalized}' has an invalid format. "
                f"Expected format: prefix + numbers (e.g., 'IR1959493')."
            )

        return normalized

    @staticmethod
    def _get_ticket_type(ticket_id: str) -> str:
        """Determine ticket type from the ID prefix."""
        if ticket_id.startswith("IR"):
            return "incident"
        elif ticket_id.startswith("SR"):
            return "servicerequest"
        else:
            raise ValueError(f"Unknown ticket type prefix in '{ticket_id}'.")

    def _extract_ticket_info(
        self, raw_ticket: dict[str, Any], ticket_id: str, ticket_type: str
    ) -> TicketInfo:
        """Extract relevant fields from the raw Athena ticket response."""
        # Handle nested field access
        def get_field(data: dict, *keys: str) -> Any:
            """Try multiple possible field names."""
            for key in keys:
                if key in data:
                    val = data[key]
                    # Handle dict values with displayName
                    if isinstance(val, dict):
                        return val.get("displayName", val.get("name", str(val)))
                    return val
            return None

        def get_nested(data: dict, outer_key: str, inner_key: str) -> Any:
            """Get a field from a nested dict."""
            outer = data.get(outer_key)
            if isinstance(outer, dict):
                return outer.get(inner_key)
            return None

        # Extract affected user details from nested object
        affected_user_obj = raw_ticket.get("affectedUser")
        affected_user_name = None
        affected_user_title = None
        affected_user_phone = None
        if isinstance(affected_user_obj, dict):
            affected_user_name = affected_user_obj.get("displayName") or affected_user_obj.get("userName")
            affected_user_title = affected_user_obj.get("title")
            affected_user_phone = affected_user_obj.get("businessPhone") or affected_user_obj.get("mobile")
        elif isinstance(affected_user_obj, str):
            affected_user_name = affected_user_obj

        # Fallback for flat format (view endpoint)
        if not affected_user_name:
            affected_user_name = raw_ticket.get("affectedUser_DisplayName")
        if not affected_user_title:
            affected_user_title = raw_ticket.get("affectedUserTitle")

        # Extract created by
        created_by_obj = raw_ticket.get("createdBy")
        created_by = None
        if isinstance(created_by_obj, dict):
            created_by = created_by_obj.get("displayName") or created_by_obj.get("userName")
        elif isinstance(created_by_obj, str):
            created_by = created_by_obj

        return TicketInfo(
            id=ticket_id,
            ticket_type=ticket_type,
            title=get_field(raw_ticket, "shortDescription", "title", "summary"),
            description=get_field(raw_ticket, "description", "details"),
            status=get_field(raw_ticket, "status"),
            priority=get_field(raw_ticket, "priority"),
            support_group=get_field(raw_ticket, "tierQueue", "supportGroup", "assignedGroup"),
            affected_user=affected_user_name,
            affected_user_title=affected_user_title,
            affected_user_phone=affected_user_phone,
            location=get_field(raw_ticket, "location"),
            floor=get_field(raw_ticket, "floor"),
            room=get_field(raw_ticket, "room"),
            classification=get_field(raw_ticket, "classificationPath", "classification"),
            source=get_field(raw_ticket, "source"),
            created_by=created_by,
            created_date=get_field(raw_ticket, "createdDate", "createDate"),
            modified_date=get_field(raw_ticket, "lastModifiedDate", "lastModified"),
        )
